// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Links.Models;

public partial class Choice
{
    public int N { get; set; }

    public int StartStageId { get; set; }

    public int EndStageId { get; set; }

    public int? OperationId { get; set; }

    public int? ScriptId { get; set; }

    public virtual Stage EndStage { get; set; }

    public virtual Stage StartStage { get; set; }
}