// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Links.Models;

public partial class Content
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Header { get; set; }

    public string Description { get; set; }

    public DateTime? CreationTime { get; set; }

    public int? Type { get; set; }

    public string Data { get; set; }

    public string DataSource { get; set; }

    public virtual Node IdNavigation { get; set; }

    public virtual ICollection<StageUserRole> StageUserRoles { get; set; } = new List<StageUserRole>();

    public virtual ICollection<Stage> Stages { get; set; } = new List<Stage>();
}