// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Links.Models;

public partial class File
{
    public int Id { get; set; }

    public byte[] FileContent { get; set; }

    public string Source { get; set; }

    public string FileName { get; set; }

    public string FileType { get; set; }

    public int? NodeId { get; set; }

    public int? RelationType { get; set; }

    public virtual Node Node { get; set; }
}