// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Links.Models;

public partial class Group
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<NodeAccess> NodeAccesses { get; set; } = new List<NodeAccess>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}