// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Links.Models;

public partial class Msg
{
    public int Id { get; set; }

    public int? NodeId { get; set; }

    public int? Author { get; set; }

    public string Text { get; set; }

    public DateTime? Dt { get; set; }

    public int? TransactionId { get; set; }

    public int? Type { get; set; }

    public virtual User AuthorNavigation { get; set; }

    public virtual ICollection<MsgforUser> MsgforUsers { get; set; } = new List<MsgforUser>();

    public virtual Node Node { get; set; }

    public virtual Transaction Transaction { get; set; }
}