// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Links.Models;

public partial class Node
{
    public int Id { get; set; }

    public string Code { get; set; }

    public int? ParentNodeId { get; set; }

    public string NodeName { get; set; }

    public string NodeContent { get; set; }

    public string Description { get; set; }

    public int? NodeTypeId { get; set; }

    public DateTime? EditTime { get; set; }

    public bool IsContainer { get; set; }

    public bool? IsActive { get; set; }

    public int? Order { get; set; }

    public virtual Content Content { get; set; }

    public virtual ICollection<Detail> Details { get; set; } = new List<Detail>();

    public virtual ICollection<File> Files { get; set; } = new List<File>();

    public virtual ICollection<History> Histories { get; set; } = new List<History>();

    public virtual ICollection<Node> InverseParentNode { get; set; } = new List<Node>();

    public virtual ICollection<Msg> Msgs { get; set; } = new List<Msg>();

    public virtual ICollection<NodeAccess> NodeAccesses { get; set; } = new List<NodeAccess>();

    public virtual NodeType NodeType { get; set; }

    public virtual Node ParentNode { get; set; }

    public virtual ICollection<Stage> Stages { get; set; } = new List<Stage>();

    public virtual ICollection<UserNode> UserNodes { get; set; } = new List<UserNode>();

 
}