// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Links.Models;

public partial class NodeType
{
    public int Id { get; set; }

    public string TypeName { get; set; }

    public string Code { get; set; }

    public string Icon { get; set; }

    public string Viewer { get; set; }

    public string Editor { get; set; }

    public virtual ICollection<Node> Nodes { get; set; } = new List<Node>();
}