// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Links.Models;

public partial class NodeAccess
{
    public int Id { get; set; }

    public int? NodeId { get; set; }

    public int? UserId { get; set; }

    public int? GroupId { get; set; }

    public int? AccessLevel { get; set; }

    public virtual Group Group { get; set; }

    public virtual Node Node { get; set; }

    public virtual User User { get; set; }
}