// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Links.Models;

public partial class ObjectDetail
{
    public int Id { get; set; }

    public int? DetailId { get; set; }

    public string Value { get; set; }

    public virtual Detail Detail { get; set; }
}