// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Links.Models;

public partial class Stage
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? ProcessId { get; set; }

    public int? N { get; set; }

    public int? TimeLimit { get; set; }

    public virtual ICollection<Choice> ChoiceEndStages { get; set; } = new List<Choice>();

    public virtual ICollection<Choice> ChoiceStartStages { get; set; } = new List<Choice>();

    public virtual Content Process { get; set; }

    public virtual Node ProcessNavigation { get; set; }

    public virtual ICollection<StageUserRole> StageUserRoles { get; set; } = new List<StageUserRole>();

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}