// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Links.Models;

public partial class StageUserRole
{
    public int UserId { get; set; }

    public int RoleId { get; set; }

    public int StageId { get; set; }

    public int? Priority { get; set; }

    public int? FormId { get; set; }

    public int? FormLink { get; set; }

    public string Template { get; set; }

    public virtual Content Form { get; set; }

    public virtual Role Role { get; set; }

    public virtual Stage Stage { get; set; }

    public virtual User User { get; set; }
}