// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Links.Models;

public partial class Transaction
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? StageId { get; set; }

    public string Data { get; set; }

    public int? Status { get; set; }

    public int? UserId { get; set; }

    public int? FlowId { get; set; }

    public DateTime? CreateDt { get; set; }

    public DateTime? ExpiryDt { get; set; }

    public DateTime? CloseDt { get; set; }

    public int? ChoiceN { get; set; }

    public virtual ICollection<Detail> Details { get; set; } = new List<Detail>();

    public virtual Transaction Flow { get; set; }

    public virtual ICollection<Transaction> InverseFlow { get; set; } = new List<Transaction>();

    public virtual ICollection<Msg> Msgs { get; set; } = new List<Msg>();

    public virtual Stage Stage { get; set; }

    public virtual ICollection<Transaction> EndTransactions { get; set; } = new List<Transaction>();

    public virtual ICollection<Transaction> StartTransactions { get; set; } = new List<Transaction>();
}