// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Links.Models;

public partial class User
{
    public int Id { get; set; }

    public string Login { get; set; }

    public string UserSettings { get; set; }

    public string Name { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string PatronimicName { get; set; }

    public DateTime? BirthDay { get; set; }

    public bool? Active { get; set; }

    public int? Summary { get; set; }

    public int? NodeId { get; set; }

    public virtual ICollection<History> Histories { get; set; } = new List<History>();

    public virtual ICollection<MsgforUser> MsgforUsers { get; set; } = new List<MsgforUser>();

    public virtual ICollection<Msg> Msgs { get; set; } = new List<Msg>();

    public virtual ICollection<NodeAccess> NodeAccesses { get; set; } = new List<NodeAccess>();

    public virtual ICollection<StageUserRole> StageUserRoles { get; set; } = new List<StageUserRole>();

    public virtual ICollection<UserNode> UserNodes { get; set; } = new List<UserNode>();

    public virtual ICollection<Group> Groups { get; set; } = new List<Group>();
}